"""GraphStore protocol. The only implementation is HydraDB — no in-process graph."""

from __future__ import annotations

from typing import Any, Protocol


class GraphStore(Protocol):
    engine: str
    query_log: list[dict[str, Any]]

    def ready(self) -> bool: ...
    def close(self) -> None: ...
    def merge_vertices(self, label: str, rows: list[dict[str, Any]], set_clause: str = "") -> int: ...
    def merge_edges(self, rel: str, rows: list[dict[str, Any]], source_label: str = "", destination_label: str = "") -> int: ...
    def find_version(self, name: str, version: str) -> dict[str, Any] | None: ...
    def lockfile_hits(self, bad_id: int, t0: int, t1: int) -> list[dict[str, Any]]: ...
    def package_pins(self, name: str) -> list[dict[str, Any]]: ...
    def many_shortest_paths(self, sources: list[int], target: int, rel: str, max_len: int = 6) -> dict[int, list[int]]: ...
    def reverse_dependents(self, bad_id: int, max_len: int = 6) -> list[dict[str, Any]]: ...
    def shared_maintainers(self, package: str) -> list[dict[str, Any]]: ...
    def shared_infra(self, package: str) -> list[dict[str, Any]]: ...
    def typosquats(self, package: str) -> list[dict[str, Any]]: ...
    def shortest_path(self, source: int, target: int, rel: str, max_len: int = 6) -> list[int]: ...
    def neighbors(self, vid: int, rel: str, *, incoming: bool = False) -> list[dict[str, Any]]: ...
    def lockfile_resolves(self, lock_id: int) -> list[dict[str, Any]]: ...
    def lockfile_pins(self, lock_id: int) -> list[dict[str, Any]]: ...
    def lockfiles_resolves(self, lock_ids: list[int]) -> dict[int, list[dict[str, Any]]]: ...
    def lockfiles_pins(self, lock_ids: list[int]) -> dict[int, list[dict[str, Any]]]: ...
    def list_services(self) -> list[dict[str, Any]]: ...
    def list_packages(self) -> list[dict[str, Any]]: ...
    def package_releases(self, name: str) -> list[dict[str, Any]]: ...
    def incident_window(self, name: str, version: str) -> dict[str, Any] | None: ...
    def list_versions(self, name: str | None = None) -> list[dict[str, Any]]: ...
    def vertex(self, vid: int) -> dict[str, Any] | None: ...
