"""Exportable incident reports."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def _iso(ts: int) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def markdown_report(result: dict[str, Any]) -> str:
    inc = result["incident"]
    summary = result["summary"]
    lines = [
        f"# HydraShield incident report",
        "",
        f"**{inc.get('title') or inc.get('slug')}**",
        "",
        f"- Package: `{inc['package']}@{inc['version']}`",
        f"- Window: {_iso(inc['start_ts'])} → {_iso(inc['end_ts'])} ({summary['window_seconds']}s)",
        f"- Engine: `{result.get('engine')}`",
        f"- Exposed: **{summary['services_exposed']}** / {summary['services_total']} services "
        f"({summary['p0_exposed']} P0, {summary['production_exposed']} production)",
        f"- Ecosystem dependents: {summary['ecosystem_dependents']}",
        f"- Typosquats: {summary['typosquats']}",
        "",
        "## Advisory",
        "",
        inc.get("advisory") or "n/a",
        "",
        "## Ranked exposure",
        "",
        "| Score | Service | Env | Team | Depth | Resolved | Path |",
        "|---:|---|---|---|---:|---|---|",
    ]
    for row in result.get("exposed") or []:
        path = " → ".join(f"{hop['name']}@{hop['version']}" for hop in row.get("path") or [])
        lines.append(
            f"| {row.get('score', 0):.2f} | `{row['name']}` | {row['env']} | {row['team']} | "
            f"{row['depth']} | {_iso(int(row['resolved_at']))} | `{path}` |"
        )
    lines += ["", "## Remediation", "", result.get("remediation", {}).get("summary") or "", ""]
    for i, step in enumerate(result.get("remediation", {}).get("steps") or [], start=1):
        extra = f" → `{step.get('to_version')}`" if step.get("to_version") else ""
        lines.append(f"{i}. Upgrade `{step['package']}`{extra}. {step.get('reason')} Residual {step.get('residual')}.")
    rotate = result.get("remediation", {}).get("rotate") or {}
    if rotate:
        lines.append(f"- {rotate.get('reason')}")
    for item in result.get("remediation", {}).get("review") or []:
        lines.append(f"- Review `{item['package']}`: {item['reason']}")
    for item in result.get("remediation", {}).get("block") or []:
        lines.append(f"- Block `{item['package']}`: {item['reason']}")
    lines += ["", "## Shared maintainers", ""]
    for row in result.get("maintainers") or []:
        lines.append(f"- `{row.get('name')}` · {row.get('npm_user')}")
    lines += ["", "## Typosquats", ""]
    for row in result.get("typosquats") or []:
        lines.append(f"- `{row.get('name')}`")
    lines += ["", "---", "", "_Generated by HydraShield. Paths are graph evidence, not scanner matches._", ""]
    return "\n".join(lines)
